Vendor relevant parts of the `pathtools` library
wandb/wandb pull request #3443
Opened 2022-03-30 19:52 UTC by dmitryduev

Description
-----------
In a fresh `pip install wandb`, we pull in the [`pathtools` library](https://github.com/gorakhargosh/pathtools) and build wheels for it before installing (it has not been updated on pypi for >6 years), which I don't like :). It has been abandoned for a very long time and is only used by our vendored `watchdog`. Because of the latter, I suggest to vendor the relevant parts of the lib.

Testing
-------
How was this PR tested?

Checklist
-------
- Name PR "[WB-NNNN][WB-MMMM] Add support for..." similar to entries in CHANGELOG.md
- Include reference to internal ticket "Fixes WB-NNNN" (and github issue "Fixes #NNNN" if applicable)

2022-03-30 20:10 UTC, dmitryduev commented
BTW @raubitsj why are we using an ancient vendored `watchdog` in the first place?

2022-04-27 23:34 UTC, raubitsj requested changes
Can you add a wandb-vendor.md (and maybe a wandb-vendor.diff) into vendor/watchdog/

2022-09-06 18:29 UTC, dmitryduev commented
@raubitsj addressed your comments. Let's get it in this time! :)

2023-10-30 21:12 UTC, kptkin approved these changes

2023-10-30 21:12 UTC, merged