Added storage_path and fixed artifact.files
wandb/wandb pull request #3969
Opened 2022-07-21 21:33 UTC by vanpelt

Fixes WB-9899

Description
-----------
This adds a new `storage_path` accessor to `artifact.files`.  It also ended up being a bit of a rabbit hole.  New additions include:

1. Moved `artifact._files(...)` to `artifact.files` and made it actually work by using the right artifact accessors.
2. Added a new `api.client.server_info` method to ask the server what versions of the sdk it supports.
3. Made the `ArtifactFiles` query only ask for `storagePath` if we're sure it has it.  There's probably a better way to do this but it works.
4. Made the `File` class use our magic `Attrs` class to simplify it's implementation.  Made me want to figure out how to get those methods to be automatically documents 🤔 

Testing
-------
Added new mocks and tested both the new server and legacy server case.

2022-07-21 22:53 UTC, annirudh approved these changes
LGTM! Thank you so much for adding this.

2022-07-21 22:53 UTC, annirudh commented on wandb/apis/public.py
> +    def version_supported(self, min_version):
This is a really nice helper -- I think I've scattered in a bunch of ad-hoc checks for the other functions here.

2022-07-22 21:08 UTC, venky-wandb commented
Awesome!! Thanks for adding this!! 💯 🥇

2022-07-22 21:08 UTC, venky-wandb approved these changes

2022-07-28 08:56 UTC, alvarobartt requested changes
Great work so far! 🎉 I was also planning also to fill a PR, as I'm working in [wandbfsspec](https://github.com/alvarobartt/wandbfsspec) and wanted to add not just the support for the File System but also to support the Artifact Store.

I checked your code and the following lines are not working:

https://github.com/wandb/wandb/blob/8dd418ba0a30da76f134743d53e7cd5b3938bfdb/wandb/apis/public.py#L4940-L4941

So I'd suggest either creating the `path` attribute and adding it to the print statement as:

```python
     return "<ArtifactFiles {} ({})>".format("/".join(self.artifact.path), len(self)) 
```

Or use the `name` instead:

```python
     return "<ArtifactFiles {} ({})>".format("/".join(self.artifact.name), len(self)) 
```

Edit: that also fails as the property `def length` is not implemented, so we'll need to create it too, I'll submit a PR over this branch in order to solve that #:hugs:

2022-07-28 10:49 UTC, alvarobartt commented
@vanpelt I've already created a PR over this branch so as to fix `__repr__` over `ArtifactFiles`, hope it's useful! 🎉

2022-08-01 01:49 UTC, merged