len-in-runs-repr
wandb/wandb pull request #5121
Opened 2023-03-09 14:29 UTC by janosh

2023-03-13 21:26 UTC, janosh commented
@gtarpenning Could you have a quick look at this?

2023-03-14 15:59 UTC, gtarpenning commented
> @gtarpenning Could you have a quick look at this?

Seems reasonable, we can probably get this into the next major python-package release :) Do you care if your name is attached to it?

2023-03-14 16:32 UTC, janosh commented
> Do you care if your name is attached to it? @janosh

I don't think such a small change warrants that but I don't mind.

2023-03-14 18:43 UTC, gtarpenning requested changes
lets just append the run count in parenthesis. Like:

`Runs janosh/testing-project (292)`

2023-03-14 18:43 UTC, gtarpenning commented on wandb/apis/public.py
> +        return f"<Runs: {len(self)} in {self.entity}/{self.project}>"
```suggestion
        return f"<Runs {self.entity}/{self.project} ({len(self)})>"
```

2023-03-14 18:43 UTC, gtarpenning commented on wandb/apis/public.py
> +        return f"<Runs: {len(self)} in {self.entity}/{self.project}>"
I think this styling is slightly preferable

2023-04-02 23:33 UTC, janosh commented
@gtarpenning Anything more needed here?

2023-05-15 03:21 UTC, closed without merging