test(integrations): Added telemetry for diffusers, trl and trlx
wandb/wandb pull request #5171
Opened 2023-03-15 18:02 UTC by ayulockin

Fixes WB-NNNN
Fixes #NNNN

Description
-----------
The PR adds telemetry for diffusers, trl and trlx.

Testing
-------
How was this PR tested?

Checklist
-------
- [ ] Include reference to internal ticket "Fixes WB-NNNN" and/or GitHub issue "Fixes #NNNN" (if applicable)
- [ ] Ensure PR title compliance with the [conventional commits standards](https://github.com/wandb/wandb/blob/main/CONTRIBUTING.md#conventional-commits)

2023-03-17 08:03 UTC, dmitryduev requested changes
Thanks @ayulockin!

We disabled all the import tests in nightly. They tend to frequently break due to third party library compatibility issues and people don't seem to have cycles to fix them. In any case, it seems that the only thing those tests actually test is telemetry and for that you can just mock out the libraries you are interested in, see: tests.pytest_tests.system_tests.test_core.test_telemetry_full.test_telemetry_imports

2023-04-04 21:54 UTC, raubitsj commented
> Hey @dmitryduev thanks for the info.
> 
> If I understand clearly, I should then revert changes made to:
> 
> * .cicleci.config.yml
> * tests/functional_tests/t0_main/imports/12-batch12-requirements.txt
> * tests/functional_tests/t0_main/imports/12-batch12.py
> * tox.ini
> 
> Instead make changes to `tests.pytest_tests.system_tests.test_core.test_telemetry_full.test_telemetry_imports`

Revert all the test changes, no need to even make a pytest_tests.   just the telemetry proto buf changes if fine.

2023-04-05 00:30 UTC, raubitsj commented on .circleci/config.yml
> +                - "imports13"
```suggestion
```

2023-04-05 00:31 UTC, raubitsj commented on tests/functional_tests/t0_main/imports/12-batch12-requirements.txt
> +git+https://github.com/CarperAI/trlx
```suggestion
```

2023-04-05 00:32 UTC, raubitsj commented on tests/functional_tests/t0_main/imports/12-batch12.py
> +    - 85 # trlx
```suggestion
```

2023-04-05 00:32 UTC, raubitsj commented on tests/functional_tests/t0_main/imports/12-batch12.py
> +import diffusers  # noqa: F401
```suggestion
```

2023-04-05 00:33 UTC, raubitsj commented on tests/functional_tests/t0_main/imports/12-batch12.py
> +import trlx  # noqa: F401
```suggestion
```

2023-04-05 00:34 UTC, raubitsj commented on tox.ini
> +            imports{1,2,3,4,5,6,7,8,9,10,11,12,13},noml,grpc}-py37,
```suggestion
            imports{1,2,3,4,5,6,7,8,9,10,11,12},noml,grpc}-py37,
```

2023-04-05 00:34 UTC, raubitsj commented on tox.ini
> +[testenv:func-s_{base,sklearn,metaflow,tf115,tf21,tf24,tf25,tf26,ray112,ray2,service,py310,docs,imports1,imports2,imports3,imports4,imports5,imports6,imports7,imports8,imports9,imports10,imports11,im
```suggestion
[testenv:func-s_{base,sklearn,metaflow,tf115,tf21,tf24,tf25,tf26,ray112,ray2,service,py310,docs,imports1,imports2,imports3,imports4,imports5,imports6,imports7,imports8,imports9,imports10,imports11,imports12,noml,grpc,kfp}-{py36,py37,py38,py39,py310}]
```

2023-04-05 00:34 UTC, raubitsj commented on tox.ini
> +    func-s_imports13-py{36,37,38,39,310}: yea {env:CI_PYTEST_SPLIT_ARGS:} --strict --shard imports13 run {posargs:--all}
```suggestion
```

2023-04-05 00:43 UTC, raubitsj approved these changes
Looks good

2023-04-05 00:52 UTC, merged

2023-04-05 08:52 UTC, ayulockin commented
> Revert all the test changes, no need to even make a pytest_tests. just the telemetry proto buf changes if fine.

Thanks @raubitsj this simplify things for adding new libraries to track.