feat(integrations): Update docstrings of the Keras callbacks
wandb/wandb pull request #5198
Opened 2023-03-20 13:33 UTC by ayulockin

Fixes WB-NNNN
Fixes #NNNN

Description
-----------
The arguments sections of the reference documentation for the Keras callbacks don't render properly. This PR will likely fix that issue.

Testing
-------
How was this PR tested?

Checklist
-------
- [ ] Include reference to internal ticket "Fixes WB-NNNN" and/or GitHub issue "Fixes #NNNN" (if applicable)
- [ ] Ensure PR title compliance with the [conventional commits standards](https://github.com/wandb/wandb/blob/main/CONTRIBUTING.md#conventional-commits)

2023-04-04 21:39 UTC, raubitsj commented
@ayulockin can you fix up the conflicts and merge.

2023-04-04 21:40 UTC, raubitsj approved these changes
LGTM

2023-04-05 00:28 UTC, raubitsj requested changes
Please fix merge conflict also

2023-04-05 00:28 UTC, raubitsj commented on wandb/integration/keras/callbacks/model_checkpoint.py
> +        save_weights_only: (bool) if True, then only the model's weights will be saved
Looks like this has a dup a few lines up.

2023-04-05 08:19 UTC, ayulockin commented
fixing conflict.

2023-04-21 01:34 UTC, kptkin approved these changes

2023-04-21 01:52 UTC, merged