fix(sdk): Fixes parameter logging for uncommon tensor types
wandb/wandb pull request #5283
Opened 2023-04-02 16:13 UTC by kooshi

Fixes #5271 

Description
-----------
What does the PR do?

Converts tensors that don't support the full api into the default tensor type in a more generic way.

Explanation
-----------
The original code was only checking for Half vs Float tensors.
Pytorch supports [many more types](https://pytorch.org/docs/stable/tensors.html) now, and most have their own tensor types as well. It is much more robust to check the underlying type, and convert it into a known supported type.

I removed the conversion of `flat` and check for `cuda` as it is now covered in the initial conversion.

Testing
-------
How was this PR tested?

I encountered the bug when training with int8 tensors. I confirmed it was reproducible, then made the change, and observed that the error was gone.

Checklist
-------
- [x] Include reference to internal ticket "Fixes WB-NNNN" and/or GitHub issue "Fixes #NNNN" (if applicable)
- [x] Ensure PR title compliance with the [conventional commits standards](https://github.com/wandb/wandb/blob/main/CONTRIBUTING.md#conventional-commits)

2023-04-04 20:41 UTC, kptkin commented
@kooshi Thanks a lot for the contribution. We will review it and try to merge it for the May release :)

2023-04-19 14:57 UTC, diegomontoya commented
@kptkin  Please have this PR review be accelerated.  This is a crash level event which should be in the top 2 in terms of priority. I see feature  prs  being reviewed/merged within 24 hours yet this has been waiting for a review for 2 weeks.

2023-08-01 19:44 UTC, dmitryduev requested changes

2023-08-01 19:44 UTC, dmitryduev commented on wandb/wandb_torch.py
> +        if tensor.dtype != torch.float32:
If this is a torch.float64 tensor, we'd lose precision. Could you please instead list the specific uncommon types that require this, in addition to HalfTensor?

2023-08-22 05:57 UTC, closed without merging