feat(integrations): Add integration with MonAI
wandb/wandb pull request #6819
Opened 2024-01-10 18:33 UTC by soumik12345

Description
-----------
Add integration with MonAI PyTorch Ignite Handlers.
- [x] Add `WandbStatsHandler` for MonAI Ignite trainer, for logging metrics during training and validation.
- [x] Add `WandbModelCheckpoint` handler for MonAI Ignite trainer, for logging model checkpoints during training.

Usage Example for `WandbStatsHandler`
---

```python
# For training
train_wandb_stats_handler = WandbStatsHandler(output_transform=lambda x: x)
train_wandb_stats_handler.attach(trainer)
# For evaluation
val_wandb_stats_handler = WandbStatsHandler(
    output_transform=lambda x: None,
    global_epoch_transform=lambda x: trainer.state.epoch,
)
val_wandb_stats_handler.attach(evaluator)
```

Usage Example for `WandbModelCheckpoint`
---

```python
checkpoint_handler = WandbModelCheckpoint(
    "./runs_dict/", "net", n_saved=10, require_empty=False
)
trainer.add_event_handler(
    event_name=Events.EPOCH_COMPLETED,
    handler=checkpoint_handler,
    to_save={"net": net, "opt": opt},
)
```
 
Testing
-------
How was this PR tested?

2024-01-12 18:32 UTC, dmitryduev requested changes
Looks great! you need to add a new shard for the functional tests to run (see the missing coverage). Also, the yea config is invalid, which trips over all the func tests.

2024-01-16 12:14 UTC, ayulockin commented on wandb/integration/monai/stats_handler.py
> +            tag_name: (str) the name of the loss tag to log. Default is "Loss".
> the name of the loss tag to log

a bit unclear

2024-01-16 12:15 UTC, ayulockin commented on wandb/integration/monai/stats_handler.py
> +        output_transform: Callable = lambda x: x[0],
I think this is an important argument and many a times the default setting might not be sufficient. I think this should show up earlier.

2024-01-31 01:39 UTC, dmitryduev commented on tests/functional_tests/t0_main/monai/test_monai_classification.yea
> +  shard: standalone-gpu
```suggestion
```

2024-01-31 02:40 UTC, dmitryduev requested changes
Thanks @soumik12345. I ran the tests on the default shard and it's erroring: https://app.circleci.com/pipelines/github/wandb/wandb/30457/workflows/fdefca75-d2e1-421f-8466-ba0625d42e0b/jobs/986798?invite=true#step-105-680
can you please look into that?

2024-02-02 18:43 UTC, dmitryduev requested changes
Looks like the relevant test is failing: https://app.circleci.com/pipelines/github/wandb/wandb/30522/workflows/84591fb4-d52e-4256-9ae6-3d2515a885e8/jobs/990365?invite=true#step-105-381
So, moving this PR to the next milestone.

2024-02-02 18:43 UTC, dmitryduev requested changes
Looks like the relevant test is failing: https://app.circleci.com/pipelines/github/wandb/wandb/30522/workflows/84591fb4-d52e-4256-9ae6-3d2515a885e8/jobs/990365?invite=true#step-105-381
So, moving this PR to the next milestone.

2024-03-06 18:43 UTC, kptkin commented on wandb/integration/monai/model_checkpoint.py
> +        n_saved: Union[int, None] = 1,
```suggestion
        n_saved: Optional[int] = 1,
```

2024-03-11 18:54 UTC, kptkin commented on wandb/integration/monai/model_checkpoint.py
> +ignite_handlers = get_module("ignite.handlers")
what happens if this is not available, i think this code will fail. Try running this without ignite installed. 
Also why do you have on line 4 direct import and on line 9 you use get_module?

2024-06-17 21:13 UTC, dmitryduev requested changes

2024-06-17 21:13 UTC, dmitryduev commented on tests/functional_tests/t0_main/monai/test_monai.yea
> +    - :wandb:runs[0][exitcode]: 0
Curiously, it looks like it fails on ci, although yea doesn't seem to catch it:
https://app.circleci.com/pipelines/github/wandb/wandb/35609/workflows/51972e1e-d502-4eda-893d-e05d98e6dfb6/jobs/1201297?invite=true#step-105-13848_46

2025-12-01 22:43 UTC, dmitryduev commented
Closing as stale and likely moot.

2025-12-01 22:43 UTC, closed without merging