Added disclaimer, removed old metniosn
wandb/wandb pull request #8089
Opened 2024-08-06 22:31 UTC by ngrayluna

Description
-----------
https://wandb.atlassian.net/browse/WB-18801

What does the PR do? Include a concise description of the PR contents.
Updates docstrings for W&B Registry.

- [ ] I updated CHANGELOG.md, or it's not applicable

Testing
-------
How was this PR tested?

2024-08-08 22:47 UTC, noaleetz commented on wandb/sdk/artifacts/artifact.py
> +            permitted by the registry you want to link the artifact to.
```suggestion
            is an accepted artifact type of the registry and collection you want to link the artifact to.
```
use language inside registry settings.

2024-08-08 22:48 UTC, noaleetz commented on wandb/sdk/artifacts/artifact.py
> -            description as markdown in the W&B App.
I still think we should keep the note on markdown - this informs to the user what they should pass in when setting a description. .

2024-08-08 22:51 UTC, noaleetz commented on wandb/sdk/artifacts/artifact.py
> +        description: A description of the artifact. View
You can also set the description programmatically - there should also be a setter than we should mention

2024-08-08 22:52 UTC, noaleetz commented on wandb/sdk/artifacts/artifact.py
> +        """Link this artifact to a project.
```suggestion
        """Link this artifact to a collection in Registry.
```

2024-08-08 22:52 UTC, noaleetz commented on wandb/sdk/artifacts/artifact.py
> +            target_path: The path inside a project.
```suggestion
            target_path: The destination path inside Registry to link the artifact to.
```

2024-08-08 22:55 UTC, noaleetz commented on wandb/sdk/artifacts/artifact.py
> +            aliases: A list of strings that uniquely identifies the artifact.
```suggestion
            aliases: A list of strings, or semantically-friendly nicknames that uniquely identify the artifact version. An alias can only point to one artifact version in a collection and can be used to programmatically reference this artifact. 
```

2024-08-08 22:55 UTC, noaleetz commented on wandb/sdk/wandb_run.py
> +        Log a model artifact version and link it to a registered model in the model registry.
```suggestion
        Log a model artifact version and link it to a registered model in the legacy model registry.
```

2024-08-08 22:58 UTC, noaleetz commented on wandb/sdk/artifacts/artifact.py
> +                `{entity}/{project}/{artifact_name}`.
```suggestion
                `{org_name}/wandb-registry-{registry_name}/{collection_name}`.
```

2024-08-08 22:58 UTC, noaleetz requested changes
requested v0 changes

2025-08-19 21:40 UTC, ngrayluna commented
Outdated + comments were caught during lazydocs revamp.

2025-08-19 21:40 UTC, closed without merging